import { NextResponse } from 'next/server'; import { prisma } from '@/lib/db/prisma'; import { ownedDevice,AuthError } from '@/lib/auth/authorize'; import { json,badRequest,error,serverError } from '@/lib/http';

/** Keep the device-detail representation identical to the list representation.
 * A physical ESP is one Device; its connected relay/sensors are DeviceCapabilities.
 */
function presentDevice(d:{id:string;deviceId:string;name:string;roomId:string;status:string;firmwareVersion:string|null;lastSeenAt:Date|null;room:{name:string};capabilities:Array<{id:string;instanceCode:string;name:string|null;config:unknown;capability:{code:string;name:string;type:string;dataType:string;unit:string|null}}>}){
  return {id:d.id,deviceId:d.deviceId,name:d.name,roomId:d.roomId,roomName:d.room.name,status:d.status,firmwareVersion:d.firmwareVersion,lastSeenAt:d.lastSeenAt,capabilities:d.capabilities.map(c=>({id:c.id,code:c.capability.code,instanceCode:c.instanceCode,name:c.name,config:c.config,type:c.capability.type,dataType:c.capability.dataType,unit:c.capability.unit}))};
}
export async function GET(_:Request,{params}:{params:Promise<{deviceId:string}>}){try{const {deviceId}=await params;const owned=await ownedDevice(deviceId);const d=await prisma.device.findUniqueOrThrow({where:{id:owned.id},include:{room:true,capabilities:{include:{capability:true}}}});return NextResponse.json(presentDevice(d));}catch(e){return e instanceof AuthError?error(e.message,e.status):serverError(e)}}
export async function PUT(request:Request,{params}:{params:Promise<{deviceId:string}>}){try{const {deviceId}=await params;const d=await ownedDevice(deviceId);const body=await json(request);if(!body||typeof body.name!=='string'||!body.name.trim())return badRequest('name is required');return NextResponse.json(await prisma.device.update({where:{id:d.id},data:{name:body.name.trim()}}));}catch(e){return e instanceof AuthError?error(e.message,e.status):serverError(e)}}
export async function DELETE(_:Request,{params}:{params:Promise<{deviceId:string}>}){try{const {deviceId}=await params;const device=await ownedDevice(deviceId);await prisma.$transaction(async(tx)=>{await tx.otaJob.deleteMany({where:{deviceId:device.id}});await tx.device.delete({where:{id:device.id}});});return new NextResponse(null,{status:204});}catch(e){return e instanceof AuthError?error(e.message,e.status):serverError(e)}}
